NON_SPECIFIED_KEY = "Non Specifie"
SERVICE_KEY = "Service"
FOREHAND_KEY = "Coup Droit"
BACKHAND_KEY = "Revers"
GROUND_REBOUND_KEY = "Rebond sur le sol"
GLASS_REBOUND_KEY = "Rebond sur la vitre"
BALL_EXCHANGE_KEY = "Echange Balle"
FOREHAND_VOLLEY_KEY = "Coup Droit Volée"
BACKHAND_VOLLEY_KEY = "Revers Volée"
BANDEJA_KEY = "Bandeja/Vibora"
FLAT_SMASH_KEY = "Flat Smash"
KICK_SMASH_KEY = "Kick Smash"
GANCHO_KEY = "Gancho Smash"
BAJADA_FOREHAND_KEY = "Bajada Forehand"
BAJADA_BACKHAND_KEY = "Bajada Backhand"
NET_KEY = "Net"
NET_TOUCH_KEY = "Net Touch"
UNKNOWN_KEY = "Unknown"

IS_LOB_KEY = "is_lob"
IS_DIAGONAL_KEY = "is_diagonal"
LOB_KEY = "Lob"
DIAGONAL_KEY = "Diagonal"

BALL_TYPES = {
    0: NON_SPECIFIED_KEY,
    1: SERVICE_KEY,
    2: FOREHAND_KEY,
    3: BACKHAND_KEY,
    4: BALL_EXCHANGE_KEY,
    5: GROUND_REBOUND_KEY,
    6: GLASS_REBOUND_KEY,
    7: FOREHAND_VOLLEY_KEY,
    8: BACKHAND_VOLLEY_KEY,
    9: BANDEJA_KEY,
    10: FLAT_SMASH_KEY,
    11: KICK_SMASH_KEY,
    12: GANCHO_KEY,
    13: BAJADA_FOREHAND_KEY,
    14: BAJADA_BACKHAND_KEY,
    15: NET_KEY,
    16: NET_TOUCH_KEY,
    17: UNKNOWN_KEY,
}
BALL_TYPE_TO_ID = {v: k for k, v in BALL_TYPES.items()}


SMASH_TYPES = [BANDEJA_KEY, FLAT_SMASH_KEY, KICK_SMASH_KEY, GANCHO_KEY]
SMASH_IDS = [BALL_TYPE_TO_ID[t] for t in SMASH_TYPES]
VOLLEY_TYPES = [FOREHAND_VOLLEY_KEY, BACKHAND_VOLLEY_KEY]
VOLLEY_IDS = [BALL_TYPE_TO_ID[t] for t in VOLLEY_TYPES]
BAJADA_TYPES = [BAJADA_FOREHAND_KEY, BAJADA_BACKHAND_KEY]
BAJADA_IDS = [BALL_TYPE_TO_ID[t] for t in BAJADA_TYPES]

HIT_BALL_TYPES = [1, 2, 3]
REBOUND_BALL_TYPES = [5, 6]

ALL_HIT_TYPES = [FOREHAND_KEY, BACKHAND_KEY] + SMASH_TYPES + VOLLEY_TYPES + BAJADA_TYPES
ALL_HIT_IDS = [BALL_TYPE_TO_ID[t] for t in ALL_HIT_TYPES]

REBOUND_IDS = [BALL_TYPE_TO_ID[t] for t in [GROUND_REBOUND_KEY, GLASS_REBOUND_KEY]]
REBOUND_ID = BALL_TYPE_TO_ID[GROUND_REBOUND_KEY]

SERVICE_ID = BALL_TYPE_TO_ID[SERVICE_KEY]
NET_TOUCH_ID = BALL_TYPE_TO_ID[NET_TOUCH_KEY]
NOTHING_ID = 0

EMPTY_BALL_TYPE_IDS = [BALL_TYPE_TO_ID[k] for k in [NON_SPECIFIED_KEY, UNKNOWN_KEY]]

BALL_TYPE_TO_ID = {v: k for k, v in BALL_TYPES.items()}


SMASH_TYPES = [BANDEJA_KEY, FLAT_SMASH_KEY, KICK_SMASH_KEY, GANCHO_KEY]
SMASH_IDS = [BALL_TYPE_TO_ID[t] for t in SMASH_TYPES]
VOLLEY_TYPES = [FOREHAND_VOLLEY_KEY, BACKHAND_VOLLEY_KEY]
VOLLEY_IDS = [BALL_TYPE_TO_ID[t] for t in VOLLEY_TYPES]
BAJADA_TYPES = [BAJADA_FOREHAND_KEY, BAJADA_BACKHAND_KEY]
BAJADA_IDS = [BALL_TYPE_TO_ID[t] for t in BAJADA_TYPES]

HIT_BALL_TYPES = [1, 2, 3]
REBOUND_BALL_TYPES = [5, 6]

ALL_HIT_TYPES = [FOREHAND_KEY, BACKHAND_KEY] + SMASH_TYPES + VOLLEY_TYPES + BAJADA_TYPES
ALL_HIT_IDS = [BALL_TYPE_TO_ID[t] for t in ALL_HIT_TYPES]

REBOUND_IDS = [BALL_TYPE_TO_ID[t] for t in [GROUND_REBOUND_KEY, GLASS_REBOUND_KEY]]
REBOUND_ID = BALL_TYPE_TO_ID[GROUND_REBOUND_KEY]

SERVICE_ID = BALL_TYPE_TO_ID[SERVICE_KEY]
NET_TOUCH_ID = BALL_TYPE_TO_ID[NET_TOUCH_KEY]
NOTHING_ID = 0

EMPTY_BALL_TYPE_IDS = [BALL_TYPE_TO_ID[k] for k in [NON_SPECIFIED_KEY, UNKNOWN_KEY]]

SERVICE_HIT_VOLLEY_SMASH_IDS = [
    BALL_TYPE_TO_ID[k]
    for k in [
        SERVICE_KEY,

        FOREHAND_KEY,
        BACKHAND_KEY,
        FOREHAND_VOLLEY_KEY,
        BACKHAND_VOLLEY_KEY,

        BANDEJA_KEY,
        FLAT_SMASH_KEY,
        KICK_SMASH_KEY,
        GANCHO_KEY,
    
        BAJADA_FOREHAND_KEY,
        BAJADA_BACKHAND_KEY,
    ]
]
EMPTY_BALL_TYPE_IDS = [BALL_TYPE_TO_ID[k] for k in [NON_SPECIFIED_KEY, UNKNOWN_KEY]]
